# Generated by Django 4.1.7 on 2023-08-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_usuario_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuario',
        ),
    ]
