# Generated by Django 4.1.7 on 2023-10-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0006_alter_usuario_options_alter_usuario_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
