# Generated by Django 4.1.7 on 2023-10-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_usuario_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='admin',
            field=models.BooleanField(default=False, verbose_name='É Admin?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='data_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='primeiro_nome',
            field=models.CharField(max_length=100, verbose_name='Primeiro Nome'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='senha',
            field=models.CharField(max_length=128, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='staff',
            field=models.BooleanField(default=False, verbose_name='É Staff?'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Último Login'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='ultimo_nome',
            field=models.CharField(max_length=100, verbose_name='Último Nome'),
        ),
    ]
