# Generated by Django 4.1.7 on 2023-10-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_alter_usuario_admin_alter_usuario_ativo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
