# Generated by Django 4.1.7 on 2023-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_usuario_admin_alter_usuario_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=100, verbose_name='Último Nome')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='E-mail')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date_registered', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('is_staff', models.BooleanField(default=False, verbose_name='É Staff?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='É Admin?')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
