# Generated by Django 4.1.7 on 2023-10-20 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_user_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='date_registered',
            new_name='date_joined',
        ),
    ]
