# Generated by Django 4.1.7 on 2023-08-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagem',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='ArquivoDigitalizado',
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
