# Generated by Django 4.1.7 on 2023-08-27 12:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id_imagem', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.ImageField(upload_to='imagens/')),
                ('ativo', models.BooleanField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imagem', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'imagem',
            },
        ),
        migrations.CreateModel(
            name='TextoDigitalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(default=datetime.datetime.now)),
                ('texto', models.TextField()),
                ('nome', models.CharField(max_length=255)),
                ('tempo_processamento', models.FloatField()),
                ('idioma', models.CharField(max_length=10)),
                ('ativo', models.BooleanField()),
                ('imagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texto_digitalizado', to='gerenciamento_texto.imagem')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='texto_digitalizado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'texto_digitalizado',
            },
        ),
    ]
