# Generated by Django 4.1.7 on 2023-08-27 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_texto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='textodigitalizado',
            options={},
        ),
        migrations.AlterModelTable(
            name='imagem',
            table='imagem',
        ),
        migrations.AlterModelTable(
            name='textodigitalizado',
            table='texto_digitalizado',
        ),
    ]
