# Generated by Django 4.1.7 on 2023-09-05 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_texto', '0002_alter_imagem_options_alter_textodigitalizado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='textodigitalizado',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
