# Generated by Django 4.1.7 on 2023-09-07 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_texto', '0003_alter_imagem_ativo_alter_textodigitalizado_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='arquivo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
