# Generated by Django 4.1.7 on 2023-09-19 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_texto', '0004_imagem_url_alter_imagem_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textodigitalizado',
            name='data_geracao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
