# Generated by Django 4.1.7 on 2023-10-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciamento_texto', '0007_remove_digitizedtext_id_alter_digitizedtext_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
